[package]
name = "delegation-contract"
version = "0.1.0"
edition = "2024"

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
